name: CI

on:
  push:
    branches:
      - main # Modify this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build the Next.js app
      run: npm run build

    - name: Run tests (if applicable)
      run: npm test
